name: mouse_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: any
  transparent_image: ^0.1.0
  path_provider: ^0.4.1
  cached_network_image: any
  intl: ^0.15.7
  image_picker: ^0.4.10
  google_maps_webservice: ^0.0.7
  flutter_youtube: ^1.1.2
  flutter_map: ^0.1.4
  random_string: ^0.0.2
  share: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/start/start1_bg.png
    - assets/images/start/start2_bg.png
    - assets/images/start/start3_bg.png
    - assets/images/start/mouse_logo.png
    - assets/images/start/google_logo.png
    - assets/images/start/vk_logo.png
    - assets/images/start/twitter_logo.png
    - assets/images/start/fb_logo.png
    - assets/images/start/login_bg.png
    - assets/images/start/signup_bg.png
    - assets/images/start/mouse_pic.png
    - assets/images/start/forgot_bg.png

    - assets/images/main/tickets_tab_icon.svg
    - assets/images/main/feed_tab_icon.svg
    - assets/images/main/shows_tab_icon.svg
    - assets/images/main/campaigns_tab_icon.svg

    - assets/images/main/profile_tab_icon.svg
    - assets/images/main/profile/account_header.png
    - assets/images/main/profile/fan_icon.png
    - assets/images/main/profile/artist_icon.png
    - assets/images/main/profile/venue_icon.png
    - assets/images/main/profile/expansion_icon.png
    - assets/images/main/profile/expainsion_up_icon.png

    - assets/images/main/shows/play_button.png
    - assets/images/main/shows/ticket_form.png
    - assets/images/main/shows/check_form.png
    - assets/images/main/shows/paypal_logo.png
    - assets/images/main/shows/credit_card.png

    - assets/images/main/settings/conv.png
    - assets/images/main/settings/copy.png
    - assets/images/main/settings/google.png
    - assets/images/main/settings/twitter.png
    - assets/images/main/settings/facebook.png

    - assets/images/main/tickets/qr.png

    - assets/images/common/pin.png
    - assets/images/common/follow_icon.png
    - assets/images/common/unfollow_icon.png
    - assets/images/common/follow_button_icon.png
    - assets/images/common/unfollow_button_icon.png
    - assets/images/common/filters_icon.svg
    - assets/images/common/blured_rect.png
    - assets/images/common/empty_account.png

  fonts:
    - family: Avenir-Black
      fonts:
        - asset: assets/fonts/Avenir-Black.ttf
    - family: Avenir-Book
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
    - family: Avenir-Heavy
      fonts:
        - asset: assets/fonts/Avenir-Heavy.ttf
    - family: Avenir-Medium
      fonts:
        - asset: assets/fonts/Avenir-Medium.ttf
    - family: AvenirNext-Medium
      fonts:
        - asset: assets/fonts/AvenirNext-Medium.ttf
    - family: AvenirNextCyr-Heavy
      fonts:
        - asset: assets/fonts/AvenirNextCyr-Heavy.ttf

    - family: Raleway-ExtraBold
      fonts:
        - asset: assets/fonts/Raleway-ExtraBold.ttf

    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
